name: CI Pipeline

on:
  pull_request:
    branches:
      - developer
      - main
      - UAT

jobs:
  unit-test:
    name: Run Unit Tests
    uses: ./.github/workflows/unit-test.yml
    with:
      node_version: '20'

  sonar-analysis:
    name: SonarQube Analysis
    needs: unit-test
    uses: ./.github/workflows/sonarqube.yml
    with:
      timeout-minutes: 5
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  snyk-security:
    name: Snyk Security Scan
    needs: unit-test
    uses: ./.github/workflows/snyk-scan.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker-build-trivy-test:
    name: Docker Image Build
    if: github.base_ref != 'developer'
    needs: 
      - unit-test
      - snyk-security
      - sonar-analysis
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: "qntmnet/qam_api"
