name: Snyk Security Scan

on:
  workflow_call:  # Allows this workflow to be triggered by another workflow
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  SnykSecurityScan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Node.js (Version 20)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Snyk to check for vulnerabilities and Update Report
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          
      - name: Run Snyk Security Test
        id: snyk_test
        continue-on-error: true  # Allow capturing output without stopping pipeline
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --severity-threshold=medium  # Fail on medium & high issues

      - name: Check Snyk Report Status
        run: |
          if [[ "${{ steps.snyk_test.outcome }}" == "success" ]]; then
            echo "✅ No vulnerabilities found. Proceeding to monitoring."
          else
            echo "❌ Vulnerabilities detected. Please Solve"
          fi
